apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - name:  nginx_ports
      containerPort: 8080
      protocol: TCP
    resources:
      limits:
        memory: "100Mi"
        cpu: "100m"
  nodeName: node01

# If pod is already created. We have create a binding object and send a post request to API serverless

#pod-binding.yaml

#apiVersion: v1
#kind: binding
#metadata:
#  name: nginx
#target:
#  apiVersion: v1
#  kind: Node
#  name: node01

# Send post request in json format: 
# curl --header "Content-Type:application/json" --request POST --data '{"apiVersion": "v1", "kind": "Binding", ...}' http://$SERVER/api/v1/namespaces/default/pods/$PODNAME/binding/



