---
apiVersion: v1
kind: ConfigMap
metadata:
   name: webapp-config-map
   namespace: default
data:
   APP_COLOR: darkblue


#Passing ConfigMap data to a container as an environment variable: (configMapRef)
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: webapp-color
  name: webapp-color
spec:
  name: webapp-color
  image: webapp-color
  imagePullPolicy: Always
  containers:
  - envFrom:
    - configMapRef:
        name: webapp-config-map
