#Here's an example of a yaml descriptor for a ConfigMap containing some data:
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: my-config-map
   namespace: default
data:
   myKey1: myValue1
   myKey2: myValue2


#Passing ConfigMap data to a container as an environment variable: (configMapKeyRef)
---
apiVersion: v1
kind: Pod
metadata:
  name: my-configmap-pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', "echo $(MY_VAR) && sleep 3600"]
    env:
    - name: MY_VAR
      valueFrom:
        configMapKeyRef:
          name: my-config-map
          key: myKey1
