---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
  namespace: default
data:
  SPECIAL_LEVEL: very
  SPECIAL_TYPE: charm




#Passing ConfigMap data to containers, in the form of file using a mounted volume:
---
apiVersion: v1
kind: Pod
metadata:
  name: my-configmap-volume-pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', "echo $(cat /etc/config/myKey) && sleep 3600"]
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: my-config-map


# When the pod runs, the command ls /etc/config/ produces the output below:
# kubectl exec -it my-configmap-volume-pod -- ls /etc/config/
# SPECIAL_LEVEL
# SPECIAL_TYPE


#If there are some files in the /etc/config/ directory, they will be deleted.
