# To provide command field to the pods
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-3
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep", "2000"]

    
---
# Create a pod with the given specifications. 
#By default it displays a 'blue' background. 
#Set the given command line arguments to change it to 'green'

apiVersion: v1
kind: Pod
metadata:
  name: webapp-green
  labels:
      name: webapp-green
spec:
  containers:
  - name: simple-webapp
    image: kodekloud/webapp-color
    args: ["--color", "green"]
