apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-31T18:39:44Z"
  name: webapp-service
  namespace: default
  resourceVersion: "1534"
  selfLink: /api/v1/namespaces/default/services/webapp-service
  uid: d594c942-0eae-4d92-8d1f-b8ec523ae713
spec:
  clusterIP: 10.105.64.201
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: webapp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}