---
apiVersion: v1
kind: Secret
metadata:
  name: secretvolume
stringData:
  myKey: myPassword

---

apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  containers:
  - name: app-container
    image: busybox
    command: ['sh', '-c', "echo $(MY_VAR) && sleep 3600"]
    volumeMounts:
      - name: secretvolume
        mountPath: /etc/certs
  volumes:
    - name: secretvolume
      secret:
        secretName: secretvolume




# Get the keys from the volume mounted to the container with the secrets:
# kubectl exec secret-volume-pod -- ls /etc/certs