# create a custom scheduler using 'custom_scheduler.yaml' file. Use schedulerName: my-scheduler to create a pod using the custom scheduler

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  -  image: nginx
     name: nginxmaster
  schedulerName: my-custom-scheduler